pr:
  branches:
    include:
      - main
      - releases/*
  paths:
    include:
      - trulens_eval

jobs:
  - job: PRBranchProtect
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        pyversion: [3.8, 3.9, 3.10, 3.11]
        testSubdirectory: ["tests/unit", "tests/unit/static"]
        exclude: 
          - testSubdirectory: "tests/unit"
            pyversion: [3.8, 3.9, 3.10] # only run full set of unit tests on 3.11
          - testSubdirectory: "tests/unit/static" # already included in parent folder
            pyversion: [3.11]

    runs-on: ${{ matrix.pyversion }}
    steps:
      - with: 
          condaEnvFileSuffix: "trulens-eval-${{ matrix.pyversion }}"
          testSubdirectory: ${{ matrix.testSubdirectory }}

      - checkout: self
        clean: true

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: |
          set -e
          conda create  -y --quiet -n $(condaEnvFileSuffix) python=$(pyversion)
          conda init bash

        displayName: Create Anaconda environment with python=$(pyversion)

      - if: $(pyversion) == 3.11 # only run format check with latest python version
        bash: |
          set -e
          source activate $(condaEnvFileSuffix)

          pip install yapf==0.32.0
          pip install isort==5.10.1

          yapf --version
          isort --vn

          ./format.sh --eval
        displayName: Format Code

      - bash: |
          num_changed_files=`git ls-files --others -m --exclude-standard ./trulens_eval | wc -l`
          if [ $num_changed_files -ne 0 ]; then
            echo "The following files have changed after running format.sh. Please format your code and update the PR."
            git ls-files --others -m --exclude-standard ./trulens_eval
            echo "\n\nOutputting git diff for checked in files.\n"
            git diff
          fi
        displayName: NoDiffCheck
      
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)

          cd ./trulens_eval
          pip install -e .

          python --version
          pip --version
          pip list

        displayName: Install trulens

      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)

          pip install ipykernel
          pip install pytest==7.0.1 pytest-azurepipelines

          python -m ipykernel install --user \
            --name $(condaEnvFileSuffix) \
            --display-name $(condaEnvFileSuffix)

        displayName: Install testing packages

      - bash: |
          source activate $(condaEnvFileSuffix)

          cd ./trulens_eval
          python -m pytest $(testSubdirectory)
        displayName: Required unit tests

      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)

          cd ./trulens_eval

          pip install -r trulens_eval/requirements.optional.txt

          python --version
          pip --version
          pip list

        displayName: Install optional packages

      - bash: |      
          python -m pytest $(testSubdirectory)

        displayName: Optional unit tests

        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)