pr:
  branches:
    include:
      - main
      - releases/*
  paths:
    include:
      - trulens_eval

jobs:
  - job: branchtest
    timeoutInMinutes: 30

    strategy:
      matrix:
        image: ["ubuntu-latest"]
        architecture: ["x64"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        tests-folder: ["tests/unit", "tests/unit/static"]
        #exclude: 
        #  - tests-folder: "tests/unit"
        #    python-version: ["3.8", "3.9", "3.10"] # only run full set of unit tests on 3.11
        #  - tests-folder: "tests/unit/static" # already included in parent folder
        #    python-version: ["3.11"]

    pool:
      vmImage: $(image)

    #env:
    #  OPENAI_API_KEY: $(OPENAI_API_KEY)
    #  HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
    #  PINECONE_API_KEY: $(PINECONE_API_KEY)
    #  PINECONE_ENV: $(PINECONE_ENV)
    #  HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)

    steps:
      - checkout: self
        clean: true

      - name: Add conda to PATH
        bash: echo "##vso[task.prependpath]$CONDA/bin"

      - name: Create Anaconda environment with python=$(python-version)
        bash: |
          set -e
          conda create -y --quiet \
            -n $(python-version) \
            python=$(python-version)

          conda init bash

      - condition: {{ eq(python-version, "3.11") }} # only run format check with latest python version
        name: Format Code
        bash: |
          set -e
          source activate $(python-version)

          pip install yapf==0.32.0
          pip install isort==5.10.1

          yapf --version
          isort --vn

          ./format.sh --eval

      - name: NoDiffCheck
        bash: |
          num_changed_files=`git ls-files --others -m --exclude-standard ./trulens_eval | wc -l`
          if [ $num_changed_files -ne 0 ]; then
            echo "The following files have changed after running format.sh. Please format your code and update the PR."
            git ls-files --others -m --exclude-standard ./trulens_eval
            echo "\n\nOutputting git diff for checked in files.\n"
            git diff
          fi

      - name: Install trulens
        bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval
          pip install -e .

          python --version
          pip --version
          pip list

      - name: Install testing packages
        bash: |
          set -e
          source activate $(python-version)

          pip install ipykernel
          pip install pytest==7.0.1 pytest-azurepipelines

          python -m ipykernel install --user \
            --name $(python-version) \
            --display-name $(python-version)

      - name: Unit tests
        bash: |
          source activate $(python-version)

          cd ./trulens_eval
          python -m pytest $(tests-folder)

      - name: Install optional packages
        bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval

          pip install -r trulens_eval/requirements.optional.txt

          python --version
          pip --version
          pip list

      - name: Unit tests with optional packages
        bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval

          python -m pytest $(tests-folder)
