trigger: none

pr:
  # Run this pipeline for any PR from a branch that starts with "releases/" that
  # changed code in trulens_eval folder or to eval notebooks in the docs folder.
  branches:
    include:
      - releases/*
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb

# schedules:
#  - cron: "0 0 * * *"
#    displayName: Daily midnight build
#    branches:
#      include:
#        - main

jobs:
  - job: ReleaseTests
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        latest:
          pythonVersion: "3.11"
          condaEnvFileSuffix: "trulens-llm"


    steps:
      - checkout: self
        clean: true

      - bash: |
          # Install pyenv and poetry
          curl https://pyenv.run | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          pyenv install $(python-version)
          pyenv local $(python-version)
          curl -sSL https://install.python-poetry.org | python3 -

          # Show python version
          which python
          python --version
        displayName: Env Setup

      - bash: |
          set -e
          poetry install --sync --verbose
        displayName: Install Packages

      - bash: |
          set -e
          echo $(which python)
          echo $(pyenv which python)
          ruff format --diff
        condition: eq(variables['python-version'], 3.12) # only run format check with latest python version
        displayName: Format Diffs

      - bash: |
          source activate $(condaEnvFileSuffix)
          python -m pytest tests/e2e
        displayName: Run e2e tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)

      - bash: |
          source activate $(condaEnvFileSuffix)
          python -m pytest tests/docs_notebooks
        displayName: Run notebook tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)
