trigger:
  branches:
    include:
      - main
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb

pr:
  branches:
    include:
      - releases/*
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main

jobs:
  - job: "All_Tests"
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        docs_notebooks:
          condaEnvFileSuffix: "trulens-llm"

    steps:
      - checkout: self
        clean: true
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - bash: |
          set -e
          conda create -y --quiet -n test_conda_env -f ./.azure_pipelines/conda.yaml
          conda init bash
        displayName: Create Anaconda environment
      - bash: |
          set -e
          source activate test_conda_env
          which python
        displayName: Which Python
      - bash: |
          set -e
          source activate test_conda_env
          cd ./trulens_eval
          pip install -e .
        displayName: Install pip package
      - bash: |
          set -e
          source activate test_conda_env
          cd ./trulens_eval
          python -m ipykernel install --user --name test_conda_env --display-name test_conda_env
        displayName: Install jupyter kernel
      - bash: |
          set -e
          source activate test_conda_env
          echo Using $(yapf --version) isort $(isort --vn)
          ./format.sh --eval
        displayName: Format Code
      - bash: |
          num_changed_files=`git ls-files --others -m --exclude-standard ./trulens_eval | wc -l`
          if [ $num_changed_files -ne 0 ]; then
            echo "The following files have changed after running format.sh. Please format your code and update the PR."
            git ls-files --others -m --exclude-standard ./trulens_eval
            echo "\n\nOutputting git diff for checked in files.\n"
            git diff
          fi
        displayName: NoDiffCheck
      - bash: |
          source activate test_conda_env
          cd ./docs/trulens_eval
          ../../.github/workflows/combine_nb_to_docs_testing.sh
        displayName: Run combine docs for testing
      - bash: |
          source activate test_conda_env
          cd ./trulens_eval
          python -m pytest ./tests
        displayName: Run tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)
