# This a definition for azure pipelines, not github pipelines. There are
# differences between these systems.

pr:
  branches:
    include:
      - main
      - releases/*
  paths:
    include:
      - trulens_eval

jobs:
  - job: pr_branch_protect
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 30

    strategy:
      matrix:
        py311:
          python-version: 3.11
          tests-folder: tests/unit
        py308-static:
          python-version: 3.8
          tests-folder: tests/unit/static
        py309-static:
          python-version: 3.9
          tests-folder: tests/unit/static
        py310-static:
          python-version: 3.10
          tests-folder: tests/unit/static

    #env:
    #  OPENAI_API_KEY: $(OPENAI_API_KEY)
    #  HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
    #  PINECONE_API_KEY: $(PINECONE_API_KEY)
    #  PINECONE_ENV: $(PINECONE_ENV)
    #  HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)

    steps:
      - checkout: self
        clean: true

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: |
          set -e
          conda create -y --quiet \
            -n $(python-version) \
            python=$(python-version)

          conda init bash
        displayName: Create Anaconda environment with python=$(python-version)

      - bash: |
          set -e
          source activate $(python-version)

          pip install yapf==0.32.0
          pip install isort==5.10.1

          yapf --version
          isort --vn

          ./format.sh --eval

          num_changed_files=`git ls-files --others -m --exclude-standard ./trulens_eval | wc -l`
          if [ $num_changed_files -ne 0 ]; then
            echo "The following files have changed after running format.sh. Please format your code and update the PR."
            git ls-files --others -m --exclude-standard ./trulens_eval
            echo "\n\nOutputting git diff for checked in files.\n"
            git diff
          fi
        # condition: eq(python-version, 3.11) # only run format check with latest python version
        displayName: NoDiffCheck

      - bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval
          pip install -e .

          python --version
          pip --version
          pip list
        displayName: Install trulens

      - bash: |
          set -e
          source activate $(python-version)

          pip install \
            ipykernel \
            pytest==7.0.1 pytest-azurepipelines

          python -m ipykernel install --user \
            --name $(python-version) \
            --display-name $(python-version)
        displayName: Install testing packages

      - bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval
          python -m pytest $(tests-folder)
        displayName: Unit tests

      - bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval

          pip install -r trulens_eval/requirements.optional.txt

          python --version
          pip --version
          pip list
        displayName: Install optional packages

      - bash: |
          set -e
          source activate $(python-version)

          cd ./trulens_eval

          python -m pytest $(tests-folder)
        env:
          # enables optional tests, see tests/unit/test.py
          with_optional: true 

        displayName: Unit tests with optional packages

