trigger: none

pr:
  # Run this pipeline for any PR from a branch that starts with "releases/" that
  # changed code in trulens_eval folder or to eval notebooks in the docs folder.
  branches:
    include:
      - releases/*
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb

# schedules:
#  - cron: "0 0 * * *"
#    displayName: Daily midnight build
#    branches:
#      include:
#        - main

jobs:
  - job: ReleaseTests
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        latest:
          python-version: 3.11


    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python-version)'

      - bash: |
          # Install poetry
          curl -sSL https://install.python-poetry.org | python3 -

          # Show python version
          which python
          python --version
        displayName: Env Setup

      - bash: |
          set -e
          poetry config virtualenvs.create false
          poetry install --sync --verbose
        displayName: Install Packages

      - bash: |
          set -e
          echo $(which python)
          echo $(pyenv which python)
          ruff format --diff
        condition: eq(variables['python-version'], 3.12) # only run format check with latest python version
        displayName: Format Diffs

      - bash: |
          poetry run pytest --rootdir=. tests/e2e
        displayName: Run e2e tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)

      - bash: |
          poetry run pytest --rootdir=. tests/docs_notebooks
        displayName: Run notebook tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)
