repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
-   repo: https://github.com/fastai/nbdev
    rev: 2.3.25
    hooks:
      - id: nbdev_clean
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.4
    hooks:
      # Run the linter.
      # - id: ruff
      #   types_or: [ python, pyi, jupyter ]
      #   args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
