repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
-   repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
    hooks:
      - id: nb-clean
        args: [--remove-empty-cells]
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        exclude: ".*poetry.lock"
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-check
        args: [-C src/core]
      - id: poetry-check
        args: [-C src/benchmark]
      - id: poetry-check
        args: [-C src/feedback]
      - id: poetry-check
        args: [-C src/instrument/langchain]
      - id: poetry-check
        args: [-C src/instrument/llamaindex]
      - id: poetry-check
        args: [-C src/instrument/nemo]
      - id: poetry-check
        args: [-C src/providers/bedrock]
      - id: poetry-check
        args: [-C src/providers/cortex]
      - id: poetry-check
        args: [-C src/providers/huggingface]
      - id: poetry-check
        args: [-C src/providers/huggingface-local]
      - id: poetry-check
        args: [-C src/providers/langchain]
      - id: poetry-check
        args: [-C src/providers/litellm]
      - id: poetry-check
        args: [-C src/providers/openai]
