[tool.poetry]
name = "trulens-llamaindex"
version = "0.33.0"
description = "Library to systematically track and evaluate LLM based applications."
authors = ["Truera Inc <all@truera.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "trulens" },
]


[tool.poetry.dependencies]
python = "^3.9"
trulens-core = {path = "../core"}
pydantic = "^2"
llama-index = "^0.10.57"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
