[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool.poetry]
name = "trulens-providers-langchain"
version = "0.33.0"
description = "Library to systematically track and evaluate LLM based applications."
authors = [
  "Truera Inc <all@truera.com>",
]
license = "MIT"
readme = "README.md"
packages = [
  { include = "trulens" },
]
homepage = "https://trulens.org/"
documentation = "https://trulens.org/trulens/getting_started/"
repository = "https://github.com/truera/trulens"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.9"
trulens-core = "^0.33"
trulens-feedback = "^0.33"
langchain = "^0.2"

[tool.poetry.group.dev.dependencies]
trulens-core = { path = "../../core" }
trulens-feedback = { path = "../../feedback" }
