[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool.poetry]
name = "trulens-core"
version = "1.0.0"
description = "Library to systematically track and evaluate LLM based applications."
authors = [
  "Truera Inc <all@truera.com>",
]
license = "MIT"
readme = "README.md"
packages = [
  { include = "trulens" },
]
homepage = "https://trulens.org/"
documentation = "https://trulens.org/trulens/getting_started/"
repository = "https://github.com/truera/trulens"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23"
munch = "^3.0"
dill = "^0.3"
tqdm = "^4.66"
typing_extensions = "^4.9"
psutil = "^5.9"
pydantic = "^2"
merkle-json = "^1.0"
sqlalchemy = "^2.0"
alembic = "^1.11"
nest-asyncio = "^1.5"
python-dotenv = "^1.0"

[tool.poetry.group.openai]
optional = true

[tool.poetry.group.openai.dependencies]
openai = "^1.37"
httpx = "^0.27"

[tool.poetry.group.snowflake]
optional = true

[tool.poetry.group.snowflake.dependencies]
snowflake-core = { version = "^0.9.0", python = "<3.12" }
snowflake-connector-python = { version = "^3.11.0", python = "<3.12" }
snowflake-snowpark-python = { version = "^1.20.0", python = "<3.12" }
snowflake-sqlalchemy = { version = "^1.6.1", python = "<3.12" }
